import { prompts } from "./prompts";
import type { GalleryTemplate } from "./types";

export const templates: GalleryTemplate[] = [
  {
    id: 1,
    title: "Sneaker Sale Poster",
    category: "Advertising",
    subcategory: "Shoes",
    description: "A modern poster for sneaker stores and promotions.",
    eyebrow: "SUMMER",
    headline: "SALE",
    subline: "UP TO 50% OFF",
    style: "from-slate-700 via-slate-800 to-black text-white",
    cover: "/summer-sale-sneaker-poster.webp",
    fields: [
      { key: "store_name", label: "Store Name", placeholder: "Veylora" },
      { key: "headline", label: "Headline", placeholder: "Summer Sale" },
      { key: "discount_offer", label: "Discount / Offer", placeholder: "Up to 50% off" },
      { key: "contact_information", label: "Contact Information", placeholder: "+43 660 1234567" },
      { key: "website_instagram", label: "Website / Instagram", placeholder: "@veylora", optional: true },
      { key: "main_color", label: "Main Color", placeholder: "#2563EB", type: "color" },
    ],
    prompt: prompts[1],
  },
  {
    id: 2,
    title: "Perfume Promotion",
    category: "E-Commerce",
    description: "Elegant luxury product promotion for a new fragrance.",
    eyebrow: "MEGA",
    headline: "SALE",
    subline: "39,99 €",
    style: "from-fuchsia-950 via-purple-800 to-pink-600 text-white",
    cover: "/perfume-promo.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Orivelle" },
      { key: "product", label: "Product Name", placeholder: "Midnight Boom" },
      { key: "campaign_headline", label: "Campaign Headline", placeholder: "Mega Sale" },
      { key: "offer", label: "Price / Offer", placeholder: "39,99 €" },
    ],
    prompt: prompts[2],
  },
  {
    id: 3,
    title: "Food Ad Poster",
    category: "Advertising",
    description: "Bold food advertising for restaurants and delivery brands.",
    eyebrow: "HOT & FRESH",
    headline: "BURGER",
    subline: "50% OFF",
    style: "from-zinc-950 via-black to-amber-950 text-white",
    cover: "/burger-template.png",
    fields: [
      { key: "restaurant", label: "Restaurant Name", placeholder: "Kravello Buns" },
      { key: "meal", label: "Headline / Product Name", placeholder: "Double Smash" },
      { key: "offer", label: "Discount / Offer", placeholder: "-50%" },
      { key: "product_type", label: "Product Type", placeholder: "Double smash burger" },
      { key: "side_dish", label: "Side Dish", placeholder: "Crispy french fries and ketchup" },
    ],
    prompt: prompts[3],
  },
  {
    id: 4,
    title: "Furniture Promo",
    category: "E-Commerce",
    description: "Minimal campaign for interiors and furniture collections.",
    keywords: ["house", "home", "living", "interior", "haus", "wohnen", "wohnzimmer", "дом", "घर", "ਘਰ"],
    eyebrow: "MINIMALIST",
    headline: "INTERIOR",
    subline: "NEW COLLECTION",
    style: "from-stone-300 via-stone-100 to-stone-400 text-stone-800",
    cover: "/furniture-promo.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Velmora Living" },
      { key: "collection", label: "Collection", placeholder: "Autumn Collection" },
      { key: "eyebrow", label: "Top Label", placeholder: "New Collection" },
      { key: "headline", label: "Headline", placeholder: "Minimalist Interior" },
      { key: "room_type", label: "Room Type", placeholder: "Scandinavian living room" },
      { key: "cta", label: "Call to Action", placeholder: "Shop now" },
    ],
    prompt: prompts[4],
  },
  {
    id: 5,
    title: "Skincare Social Post",
    category: "Social Media",
    description: "Clean beauty campaign for skincare launches.",
    eyebrow: "GLOW",
    headline: "NATURALLY",
    subline: "NEW SKINCARE LINE",
    style: "from-amber-100 via-orange-50 to-rose-200 text-stone-800",
    cover: "/skincare-serum.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Lumevara" },
      { key: "product", label: "Product", placeholder: "Vitamin C Serum" },
      { key: "claim", label: "Main Benefit", placeholder: "Natural radiance" },
      { key: "headline", label: "Headline", placeholder: "Glow Natural" },
      { key: "subheadline", label: "Subheadline", placeholder: "New Skincare Line" },
    ],
    prompt: prompts[5],
  },
  {
    id: 6,
    title: "Tech Product Ad",
    category: "Electronics",
    description: "Premium dark launch visual for modern technology.",
    eyebrow: "NEW",
    headline: "TECHNOLOGY",
    subline: "NEW EXPERIENCE",
    style: "from-black via-zinc-900 to-slate-700 text-white",
    cover: "/tech-headphones.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Zyphreon" },
      { key: "product", label: "Product Name", placeholder: "Air Pro Headphones" },
      { key: "feature", label: "Key Feature", placeholder: "Immersive sound" },
      { key: "headline", label: "Headline", placeholder: "New Technology" },
      { key: "subheadline", label: "Subheadline", placeholder: "New Experience" },
    ],
    prompt: prompts[6],
  },
  {
    id: 7,
    title: "Real Estate Flyer",
    category: "Real Estate",
    description: "Modern property flyer for agents and developers.",
    keywords: ["house", "home", "property", "villa", "haus", "immobilie", "zuhause", "дом", "вилла", "घर", "मकान", "ਘਰ"],
    eyebrow: "MODERN",
    headline: "LIVING",
    subline: "FIND YOUR DREAM HOME",
    style: "from-sky-900 via-blue-600 to-stone-300 text-white",
    cover: "/real-estate-villa.webp",
    coverFit: "contain",
    fields: [
      { key: "agency", label: "Agency Name", placeholder: "Avenquor Estates" },
      { key: "property", label: "Property Type", placeholder: "Modern Villa" },
      { key: "location", label: "Location", placeholder: "Vienna" },
      { key: "headline", label: "Headline", placeholder: "Modern Living - Find Your Dream Home" },
      { key: "bedrooms", label: "Bedrooms", placeholder: "4 Bedrooms" },
      { key: "bathrooms", label: "Bathrooms", placeholder: "4 Bathrooms" },
      { key: "area", label: "Living Area", placeholder: "450 m²" },
      {
        key: "features",
        label: "Property Features",
        placeholder: "Infinity Pool • Smart Home • Private Garden",
      },
      {
        key: "listing_details",
        label: "Listing Details",
        placeholder: "Prime Location • District 19, Vienna",
      },
      { key: "contact", label: "Contact Number", placeholder: "+43 1 234 5678" },
      { key: "email", label: "Email Address", placeholder: "office@avenquorestates.com", optional: true },
      { key: "website", label: "Website", placeholder: "www.avenquorestates.com" },
      { key: "cta", label: "Call to Action", placeholder: "Book a Private Viewing Today" },
    ],
    prompt: prompts[7],
  },
  {
    id: 8,
    title: "Fashion Lookbook",
    category: "Fashion",
    subcategory: "Lookbooks",
    description: "Editorial campaign for a new fashion collection.",
    keywords: ["dress", "dresses", "clothing", "kleid", "kleider", "modekleid", "платье", "पोशाक", "ਡਰੈੱਸ"],
    eyebrow: "NEW",
    headline: "COLLECTION",
    subline: "SHOP NOW",
    style: "from-rose-300 via-pink-200 to-rose-100 text-rose-900",
    cover: "/fashion-lookbook.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Atelier Virelune" },
      { key: "season", label: "Collection", placeholder: "Summer 2026" },
      { key: "headline", label: "Headline", placeholder: "New Collection" },
      { key: "garment", label: "Garment", placeholder: "Flowing summer maxi dress" },
      { key: "garment_color", label: "Garment Color", placeholder: "Light pink" },
      { key: "cta", label: "Call to Action", placeholder: "Shop now" },
    ],
    prompt: prompts[8],
  },
  {
    id: 9,
    title: "Event Promotion",
    category: "Seasonal",
    description: "Energetic poster for festivals and live events.",
    eyebrow: "SUMMER",
    headline: "FESTIVAL",
    subline: "20–22 JUNE",
    style: "from-orange-600 via-orange-500 to-amber-300 text-white",
    cover: "/summer-festival.webp",
    coverFit: "contain",
    fields: [
      { key: "event", label: "Event Name", placeholder: "Summer Festival" },
      { key: "event_type", label: "Event Type", placeholder: "Summer music festival" },
      { key: "date", label: "Date", placeholder: "20–22 June" },
      { key: "location", label: "Location", placeholder: "Vienna" },
      { key: "country", label: "Country", placeholder: "Austria" },
    ],
    prompt: prompts[9],
  },
  {
    id: 10,
    title: "Watch Collection",
    category: "E-Commerce",
    description: "Timeless premium campaign for luxury accessories.",
    eyebrow: "LUXURY",
    headline: "WATCHES",
    subline: "TIMELESS ELEGANCE",
    style: "from-neutral-950 via-stone-900 to-amber-900 text-white",
    cover: "/luxury-watch.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Maison Orvessa" },
      { key: "collection", label: "Collection", placeholder: "Noir Collection" },
      { key: "headline", label: "Headline", placeholder: "Luxury Watch" },
      { key: "slogan", label: "Slogan", placeholder: "Timeless Elegance" },
      { key: "watch_color", label: "Watch Color", placeholder: "Black" },
      { key: "cta", label: "Call to Action", placeholder: "Discover more" },
    ],
    prompt: prompts[10],
  },
  {
    id: 11,
    title: "Shoes Promotion",
    category: "Fashion",
    subcategory: "Shoes",
    description: "Clean launch campaign for footwear and accessories.",
    eyebrow: "NEW",
    headline: "ARRIVALS",
    subline: "STEP INTO STYLE",
    style: "from-stone-200 via-amber-50 to-stone-400 text-stone-900",
    cover: "/cloud-runner.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Norynth" },
      { key: "product", label: "Product Name", placeholder: "Cloud Runner" },
      { key: "headline", label: "Headline", placeholder: "New Arrival" },
      { key: "slogan", label: "Slogan", placeholder: "Step Into Style" },
      { key: "shoe_color", label: "Shoe Color", placeholder: "White and beige" },
      { key: "cta", label: "Call to Action", placeholder: "Explore now" },
    ],
    prompt: prompts[11],
  },
  {
    id: 12,
    title: "Accessories Promo",
    category: "Fashion",
    subcategory: "Accessories",
    description: "Refined editorial promotion for timeless accessories.",
    eyebrow: "TIMELESS",
    headline: "ELEGANCE",
    subline: "NEW COLLECTION",
    style: "from-amber-100 via-stone-100 to-amber-300 text-stone-800",
    cover: "/luxury-handbag.webp",
    coverFit: "contain",
    fields: [
      { key: "brand", label: "Brand Name", placeholder: "Maison Elvaris" },
      { key: "product", label: "Product", placeholder: "Leather Handbag" },
      { key: "headline", label: "Headline", placeholder: "Timeless Elegance" },
      { key: "subheadline", label: "Subheadline", placeholder: "New Collection" },
      { key: "product_color", label: "Product Color", placeholder: "Beige" },
      { key: "cta", label: "Call to Action", placeholder: "Discover the collection" },
    ],
    prompt: prompts[12],
  },
];
